# Generated by Django 6.0.2 on 2026-03-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('GEN', 'General'), ('TECH', 'Technology'), ('BOOK', 'Books'), ('LIFE', 'Lifestyle'), ('HOBB', 'Hobbies')], default='GEN', max_length=4, verbose_name='Category'),
        ),
    ]
